services:
  playwright-test:
    image: playwright-test
    build:
      context: .
      dockerfile: ./Dockerfile
    command:
      npx playwright test --retries=1
    volumes:
      - ./playwright-report:/app/playwright-report
      - ./test-results:/app/test-results
    
